# Generated by Django 5.0.3 on 2024-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightcomparison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_location_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_location_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='layover_location_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='layover_location_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=200),
        ),
    ]
