# Generated by Django 5.0.2 on 2024-03-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightcomparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=200)),
                ('firstSeen', models.IntegerField()),
                ('estDepartureAirport', models.CharField(max_length=10)),
                ('lastSeen', models.IntegerField()),
                ('estArrivalAirport', models.CharField(max_length=10)),
                ('callsign', models.CharField(max_length=8)),
                ('estDepartureAirportHorizDistance', models.IntegerField()),
                ('estDepartureAirportVertDistance', models.IntegerField()),
                ('estArrivalAirportHorizDistance', models.IntegerField()),
                ('estArrivalAirportVertDistance', models.IntegerField()),
                ('departureAirportCandidatesCount', models.IntegerField()),
                ('arrivalAirportCandidatesCount', models.IntegerField()),
            ],
        ),
    ]
